version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: note_user
      POSTGRES_PASSWORD: note_pwd123
      POSTGRES_DB: notes_db
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notes_test
